volumes:
  #
  # *_home volumes are the /home/arcgis directories
  # and the software for each service gets installed there.
  #
  # *_data volumes are where the data for each services gets stored.
  #
  portal_home:
    name: arcgis_portal_home
  portal_data:
    name: arcgis_portal_data
  server_home:
    name: arcgis_server_home
  server_data:
    name: arcgis_server_data
  datastore_home:
    name: arcgis_datastore_home
  datastore_data:
    name: arcgis_datastore_data
  postgres_data:
    name: arcgis_postgres_data
  pgadmin_data:
    name: arcgis_pgadmin_data

networks:
  arcgis_network:
    driver: bridge

services:
  server:
    platform: linux/amd64
    image: arcgis-server
    hostname: ${GISSERVER}
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file: ./.env
    environment:
      - ESRI_VERSION=${ESRI_VERSION}
      - AGS_USERNAME=${USERNAME}
      - AGS_PASSWORD=${PASSWORD}
    ports:
      - "6080:6080"
      - "6443:6443"
    ulimits:
      nofile:
        soft: 70000
        hard: 70000
      nproc:
        soft: 30000
        hard: 30000
    volumes:
      - ./Installers/ArcGISServer:/app/Installer:ro
      - ./Licenses/ArcGISServer.prvc:/app/server.prvc:ro
      - ./Licenses/authorization.ecp:/app/server.ecp:ro
      - ./configurebasedeployment.properties:/app/configurebasedeployment.properties:rw
      - server_home:/home/arcgis:rw
      - server_data:/srv/directories:rw
    networks:
      - arcgis_network

  portal:
    platform: linux/amd64
    image: arcgis-portal
    hostname: ${PORTAL}
    build:
      context: ./portal
      dockerfile: Dockerfile
    env_file: ./.env
    environment:
      - ESRI_VERSION=${ESRI_VERSION}
      - AGP_USERNAME=${USERNAME}
      - AGP_PASSWORD=${PASSWORD}
      - PORTAL_CONTENT=/home/arcgis/content
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@example.com}
    ports:
      - "7080:7080"
      - "7443:7443"
    ulimits:
      nofile:
        soft: 70000
        hard: 70000
      nproc:
        soft: 30000
        hard: 30000
    volumes:
      - ./Installers/PortalForArcGIS:/app/Installer:ro
      - ./Licenses/ArcGISPortal.json:/app/portal_license.json:ro
      - portal_home:/home/arcgis:rw
      - portal_data:/home/arcgis/content:rw
    networks:
      - arcgis_network

  datastore:
    platform: linux/amd64
    image: arcgis-datastore
    hostname: ${DATASTORE}
    build:
      context: ./datastore
      dockerfile: Dockerfile
    env_file: ./.env
    environment:
      - ESRI_VERSION=${ESRI_VERSION}
      - AGE_SERVER=${GISSERVER}
      - AGS_USERNAME=${USERNAME}
      - AGS_PASSWORD=${PASSWORD}
    ports:
      - "2443:2443"
      - "9876:9876"
    ulimits:
      nofile:
        soft: 70000
        hard: 70000
      nproc:
        soft: 30000
        hard: 30000
    volumes:
      - ./Installers/ArcGISDataStore_Linux:/app/Installer:ro
      - datastore_home:/home/arcgis:rw
    networks:
      - arcgis_network

  postgres:
    platform: linux/amd64
    image: postgres
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - arcgis_network

  pgadmin:
    platform: linux/amd64
    image: dpage/pgadmin4:latest
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    env_file: .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_DISABLE_POSTFIX: 1
    networks:
      - arcgis_network

  nginx-proxy:
    image: docker.io/library/nginx:alpine
    ports:
      - "8081:80"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf:ro
    networks:
      - arcgis_network
