volumes:
#
# *_home volumes are the /home/arcgis directories
# and the software for each service gets installed there.
#
# *_data volumes are where the data for each services gets stored.
#
  portal_home:
    name: arcgis_portal_home
  portal_data:
    name: arcgis_portal_data
  server_home:
    name: arcgis_server_home
  server_data:
    name: arcgis_server_data
  datastore_home:
    name: arcgis_datastore_home
  datastore_data:
    name: arcgis_datastore_data
  postgres_data:
    name: arcgis_postgres_data
  pgadmin_data:
    name: arcgis_pgadmin_data

services:
  server:
    image: arcgis-server
    hostname: ${GISSERVER}
    build: 
      context: ./server
      dockerfile: Dockerfile
    env_file: ./.env
    environment:
      - ESRI_VERSION=${ESRI_VERSION}
      - AGS_USERNAME=${USERNAME}
      - AGS_PASSWORD=${PASSWORD}
    ports:
      - "6080:6080"
      - "6443:6443"
    volumes:
      - ./Installers/ArcGISServer:/app/Installer:ro
      - ./Licenses/ArcGISServer.prvc:/app/server.prvc:ro
      - ./configurebasedeployment.properties:/app/configurebasedeployment.properties:rw
      - server_home:/home/arcgis:rw
      - server_data:/srv/directories:rw
#      - server_config:/home/arcgis/server/usr/config-store
#      - server_logs:/home/arcgis/server/usr/logs
    # Uncomment the next three lines to work in a shell environment for debugging. (See exec_server)
    #entrypoint: /bin/bash
    #stdin_open: true
    #tty: true

  portal:
    image: arcgis-portal
    hostname: ${PORTAL}
    build:
      context: ./portal
      dockerfile: Dockerfile
    env_file: ./.env
    environment:
      - ESRI_VERSION=${ESRI_VERSION}
      - AGP_USERNAME=${USERNAME}
      - AGP_PASSWORD=${PASSWORD} 
      - PORTAL_CONTENT=/home/arcgis/content
    ports:
      - "7080:7080"
      - "7443:7443"
    volumes:
      - ./Installers/PortalForArcGIS:/app/Installer:ro
      - ./Licenses/ArcGISPortal.json:/app/portal_license.json:ro
      - portal_home:/home/arcgis:rw
      - portal_data:/srv/content:rw
     #- portal_data:/home/arcgis/portal/usr/arcgisportal:rw
    links:
      - server
      - datastore
    # Uncomment the next three lines to work in a shell environment for debugging.
#    entrypoint: /bin/bash
#    stdin_open: true
#    tty: true

  datastore:
    image: arcgis-datastore
    hostname: ${DATASTORE}
    build: 
      context: ./datastore
      dockerfile: Dockerfile
    env_file: ./.env
    environment:
      - ESRI_VERSION=${ESRI_VERSION}
      - AGE_SERVER=${GISSERVER}
      - AGS_USERNAME=${USERNAME}
      - AGS_PASSWORD=${PASSWORD} 
    ports:
      - "2443:2443"
      - "9876:9876"
    volumes:
      - ./Installers/ArcGISDataStore_Linux:/app/Installer:ro
      - datastore_home:/home/arcgis:rw
# where does this belong
#      - datastore_data:/home/arcgis/?????:rw
    links:
      - server
    # Uncomment the next three lines to work in a shell environment for debugging.
    #entrypoint: /bin/bash
    #stdin_open: true
    #tty: true

  postgres:
    image: postgres
    build:
      context: .
      dockerfile: Dockerfile.postgres
    ports:
      # Allow access to this database from our LAN
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sh:/docker-entrypoint-initdb.d/init.sh:ro
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "8213:80"
    volumes:
      # Session data, user files, config files, config database go here.
      - pgadmin_data:/var/lib/pgadmin
    env_file: .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_DISABLE_POSTFIX: 1

  mcp:
    image: arcgis-fastapi-server
    hostname: mcp
    build:
      context: ./mcp
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    env_file: ./.env
    environment:
      - ARCGIS_SERVER_URL=https://${GISSERVER}:6443/arcgis/rest/services
      - ARCGIS_PORTAL_URL=https://${PORTAL}:7443
      - ARCGIS_USERNAME=${MCP_USERNAME}
      - ARCGIS_PASSWORD=${MCP_PASSWORD}
      - DEBUG=${DEBUG:-false}
    volumes:
      - ./mcp:/app:rw

  agent:
    image: arcgis-langchain-agent
    hostname: agent
    build:
      context: ./agent
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file: ./.env
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - MCP_SERVER_URL=http://mcp:8001/mcp
      - DEBUG=${DEBUG:-false}
    volumes:
      - ./agent:/app:rw
